### ISSUE TITLE
Dropdownmenü funktioniert leider nicht richtig

### ISSUE THREAD

**Issue by einfachich** [Bloggerschmidt/Blank#55]
Hallo,

ich bin momentant dran an einen Blank Template zu basten und komme einfach bei den Dropdownmenü nicht weiter... Google hilft mir nicht weiter da es mir zu viel von der Vörgängerversion von Bootstrap vorschlägt.

folgendes Problem. Das Menü zeigt es richtig an, aber sobald ich auf ein Link klicke wo auch das Menü aufgehen sollte passiert nichts. Erst wenn ich drauf klicke kommt kurz das Menü und schließt wieder.

Würde mich freue über Antworten.

Lg Tobias

**Comment by nn-medienagentur** [comment]
liegt meistens an der /media/jui/js/bootstrap.min.js die wird zum Beispiel geladen wenn man noch Breadcrumbs aktiviert hat als Modul.
