### ISSUE TITLE
Falsches Dropdownverhalten bei Menüeintrag-Alias ohne Unterpunkte

### ISSUE THREAD

**Issue by alex-schell** [Bloggerschmidt/Blank#64]
Wenn man einen Menüpunkt als "Menüeintrag-Alias" definiert wird aus dem Menüpunkt ein Bootstrap-Dropdown, sprich es wird ein [data-toggle="dropdown"] gesetzt, obwohl es gar keine Unterpunkte und somit kein Untermenü gibt.

Richtig wäre hier, das [data-toggle="dropdown"] nur zu triggern, wenn der Menüpunkt auch ein "Parent" ist, sprich Unterpunkte besitzt. Dazu muss man folgende Zeile anpassen:

Bootstrap-Template-3.3.0 ▸ html ▸ mod_menu ▸ default_url.php
Zeile 33 ersetzen durch:

```
if($item->parent) { ?>
  <a data-toggle="dropdown" <?php echo $class; ?>href="<?php echo $flink; ?>" <?php echo $title; ?>><?php echo $linktype; ?> <i class="fa fa-caret-down"></i></a>
<?php } else { ?>
  <a <?php echo $class; ?>href="<?php echo $flink; ?>" <?php echo $title; ?>><?php echo $linktype; ?></a>
<?php }
```

**Comment by drmenzelit** [comment]
Das Problem hatte ich auch mit "Externe URL" Menütyp. Ich habe erstmal den Override für default_url.php entfernt...

**Comment by Bloggerschmidt** [comment]
This issue was moved to Bloggerschmidt/Blank-Bootstrap-Edition#8
