### ISSUE TITLE
Use builtin less compiler

### ISSUE THREAD

**Issue by smehrbrodt** [Bloggerschmidt/Blank#66]
Is there a reason why you include your own version of lessphp and not use the existing Joomla Library [JLess](https://github.com/joomla/joomla-cms/blob/staging/build/generatecss.php#L68)?

**Comment by Bloggerschmidt** [comment]
The reason is simple: I didn't know that JLess exists. But I think also that it isn't a good way to compile. We should compile, compress and concatenate local, e.g. with gulp, and then upload it (back to the old way). What do you think?

**Comment by renekreijveld** [comment]
If you want to use an onboard Less compiler I would prefer to use http://lessphp.gpeasy.com.
While Samuel has a good point to use JLess I am not sure of this one is up-to-date and capable of generating Map files. The less compiler at http://lessphp.gpeasy.com can generate Map files and much more. The advantage of using an onboard Less compiler for me is the ability to alter some less code on the server side and immediately see the results.

**Comment by Bloggerschmidt** [comment]
Yes, the maintenance of a website is better with an onboard less compiler. But only if you work on webspace. If you work with git your workflow is local and can be combined with gulp very well.
