### ISSUE TITLE
Newsletter Anmeldung

### ISSUE THREAD

**Issue by AndiLeni** [Bloggerschmidt/Blank#69]
Hallo,
ich wollte nur schnell mitteilen das die Einschreibung zum Newsletter auf der Homepage nicht funktioniert.

**Comment by Bloggerschmidt** [comment]
Danke für die Info. Die Einschreibung ist nun wieder möglich.

**Comment by AndiLeni** [comment]
Keine Ursache. Hat mich gefreut das ich helfen konnte.

Andi

2016-01-15 11:46 GMT+01:00 Alexander Schmidt <notifications@github.com>:
