### ISSUE TITLE
Error in logic.php

### ISSUE THREAD

**Issue by Loschdi** [Bloggerschmidt/Blank#71]
I install the Template local with the following Errors. Can you help me out?

Notice: Undefined index: media in C:\xampp2\htdocs\bs\templates\frontend\logic.php on line 71

Notice: Undefined index: async in C:\xampp2\htdocs\bs\templates\frontend\logic.php on line 77

Notice: Undefined index: defer in C:\xampp2\htdocs\bs\templates\frontend\logic.php on line 78

Notice: Undefined index: async in C:\xampp2\htdocs\bs\templates\frontend\logic.php on line 77

Notice: Undefined index: defer in C:\xampp2\htdocs\bs\templates\frontend\logic.php on line 78

Notice: Undefined index: async in C:\xampp2\htdocs\bs\templates\frontend\logic.php on line 77

Notice: Undefined index: defer in C:\xampp2\htdocs\bs\templates\frontend\logic.php on line 78

Notice: Undefined index: async in C:\xampp2\htdocs\bs\templates\frontend\logic.php on line 77

Notice: Undefined index: defer in C:\xampp2\htdocs\bs\templates\frontend\logic.php on line 78

Notice: Undefined index: async in C:\xampp2\htdocs\bs\templates\frontend\logic.php on line 77

Notice: Undefined index: defer in C:\xampp2\htdocs\bs\templates\frontend\logic.php on line 78

**Comment by Bloggerschmidt** [comment]
Hm, unfortunalty, the original logic.php has only 19 lines of code. So, I guess it is custom code. Anyway, it is not an error, it is a notice. If your error reporting is standard, this issue disappears.
